# Generated by Django 3.2.7 on 2021-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(related_name='shopping_cart', to='recipes.Recipe'),
        ),
    ]
