# Generated by Django 3.2.7 on 2021-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='recipes',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipe'),
        ),
    ]
